import sqlite3 
conn = sqlite3.connect('data/nyc_taxi.db') 
cursor = conn.cursor() 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "total_trips", COUNT(*) FROM trips') 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "total_trips", COUNT(*) FROM trips') 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "avg_fare", ROUND(AVG(fare_amount),2) FROM trips') 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "avg_distance", ROUND(AVG(trip_distance),2) FROM trips') 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "avg_duration_mins", ROUND(AVG(trip_duration_mins),2) FROM trips') 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "avg_speed_mph", ROUND(AVG(avg_speed_mph),2) FROM trips') 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "avg_tip_percentage", ROUND(AVG(tip_percentage),2) FROM trips') 
cursor.execute('INSERT INTO summary_stats (stat_name, stat_value) SELECT "avg_tip_percentage", ROUND(AVG(tip_percentage),2) FROM trips') 
conn.commit() 
conn.close() 
print('Done!') 
